### ISSUE TITLE
cmake . fails on MacOS (Ventura 13.5)

### ISSUE THREAD

**Issue by gasparschott** [ImageProcessing-ElectronicPublications/scantailor-advanced#4]
CMake Error at core/CMakeLists.txt:140 (translation_sources):
  Unknown CMake command "translation_sources".

**Comment by zvezdochiot** [comment]
Hi @gasparschott .

Go to mainstrim: https://github.com/ScanTailor-Advanced/scantailor-advanced . It's just a fork.
