### ISSUE TITLE
"license-gpl" missing dependency

### ISSUE THREAD

**Issue by zbgns** [ImageProcessing-ElectronicPublications/scantailor-advanced#5]
I try to install scantailor-advanced using `scantailor-advanced_1.0.19-deb11bg_amd64.deb` binary.  I have the following message while installing:
```
scantailor-advanced depends on license-gpl; however:
  Package license-gpl is not installed.
```
Remaining dependencies seem to be met and the application starts. However, each time I run `apt` there is a message about unsolved dependency and there is suggestion to remove scantailor-advanced by `sudo apt autoremove`.

I have no idea, how to install the missing `license-gpl` package.

The OS is Debian 11 (bullseye) linux subsystem into Chrome OS, as I try to install the app on a chromebook.

Any suggestions would be appreciated. 

I'm really grateful that you took care of the scantailor-advanced and scantailor-experimental development, by the way.

Regards
zbgns

**Comment by zvezdochiot** [comment]
Hi @zbgns .

Rub your eyes and take a closer look at the releases. Each release contains a package `license-gpl_3.0-20171206_all.deb`.

**Comment by zbgns** [comment]
Oh, that was nasty. Thanks, now it works.
