### ISSUE TITLE
Pick color (Fill zones) doesn't work properly in the Qt6 version

### ISSUE THREAD

**Issue by iG8R** [ImageProcessing-ElectronicPublications/scantailor-advanced#6]
Hi.
As title says the function of picking a color in the Fill zones mode doesn't work properly, e.g. picks a wrong color, in the Qt6 version (ScanTailor-Advanced-1.0.19.win-x64.zip), although in the Qt5 version (scantailor-advanced_1.0.19-qt5_win64.zip) everything is fine.

**Comment by zvezdochiot** [comment]
Hi @iG8R .

This is not the only complaint about this assembly. But this is the official build from [Scantailor-Advanced](https://github.com/ScanTailor-Advanced/scantailor-advanced). If you have any complaints, please contact the manufacturers, that is, the [official repository](https://github.com/ScanTailor-Advanced/scantailor-advanced) where it was taken from.

If you have any complaints about our build (on Qt5), write here.

**Comment by iG8R** [comment]
Thanks a lot for the quick reply.
The issue appeared to be a little intricate - it is related to the "enable_opengl=true" option.
https://github.com/ScanTailor-Advanced/scantailor-advanced/issues/89
