### ISSUE TITLE
Выделение текущей страницы в темной теме

### ISSUE THREAD

**Issue by hooddy** [ImageProcessing-ElectronicPublications/scantailor-advanced#7]
Хочется попросить более контрастно выделять текущую страницу в правом блоке при темной теме. Потому что серое на черном как-то так себе, сливается, сложно сфокусироваться сразу. Ок, может быть серое, но еще обводку сделать синюю, как у других элементов в блоке слева и в центральном окне. А то и красную...

**Comment by zvezdochiot** [comment]
@hooddy добавляйте скриншот, закидывайте его в картинко-помойку и прикрепляйте к описанию:
```
![alt text](url to image)
```
Желательно добавлять стрелочки. Иначе с ваших слов ничего не понятно.

PS: Данный репо является лишь форком основного: https://github.com/ScanTailor-Advanced/scantailor-advanced - и был создан только для расширения списка порогов и зонального функционала. Плюс к этому имеет собственную сборку под винду на Qt5. Но все PR уже давно отправлены и слиты.

**Comment by hooddy** [comment]
![Безымянный](https://github.com/ImageProcessing-ElectronicPublications/scantailor-advanced/assets/6899176/4c8341d9-7521-4a7d-9eb6-a342a037afd4)
вместо тысячи слов. правый блок обведено, как мне кажется лучше. без обводки текущей страницы сфокусироваться сложно. вам не писал лично, ваш экспериментальный форк без темной темы, точнее вы ее убрали. если это все меняется на уровне исходного приложения, то запулите туда.

**Comment by hooddy** [comment]
мне на самом деле не хватает адекватного инструмента для выделения прямоугольных картинок как в графических редакторах, т.е. зажать мышь и выделить прямоугольник. и затем было бы вообще супер удобно эти границы также мышью передвигать, т.е. поднести к стороне выделения (или даже углу), зажать на нее и передвинуть, т.е. уменьшить или увеличить. куда про это написать?

**Comment by zvezdochiot** [comment]
@hooddy say:
>куда про это написать?

Наверное, в спортлото. Ваши хотелки обслуживаются только профессиональными прогерами за денюжку. На гите от них никакого отклика не ждите. Такие вот дела. ;)

**Comment by hooddy** [comment]
очень жаль. элементарные разумные вопросы. то что вы нахуевертили кучу там реально профессиональных веще вот по мне так это за денги делается, все эти слои, формулы, вычисления. а тупо выделялку добавить... ну и похуй тогда, раз такое отношение.

**Comment by hooddy** [comment]
всем насрать
